spring:
  application:
    name: bookcatalog-api
  datasource:
    username: 
    password: 
    url: jdbc:mysql://bookdb.canc066u4jor.us-east-1.rds.amazonaws.com/bookdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 5000
	
	