spring:
  application:
    name: bookcatalog-api
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jfsjunbatch
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081